--- #YAML:1.0
name: File-System
version: 1.13
author:
  - Andrew Sterling Hanenkamp, E<lt>hanenkamp@users.sourceforge.netE<gt>
abstract: A virtual file system written in pure Perl
license: perl
generated_by: Module::Build version 0.261, without YAML.pm
