---
name: File-System
version: 1.12
author:
  - Andrew Sterling Hanenkamp, E<lt>hanenkamp@users.sourceforge.netE<gt>
abstract: A virtual file system written in pure Perl
license: perl
requires:
  File::Copy::Recursive: 0.05
  Parse::RecDescent: 1.94
provides:
  File::System:
    file: lib/File/System.pm
    version: 1.12
  File::System::Layered:
    file: lib/File/System/Layered.pm
    version: 1.06
  File::System::Object:
    file: lib/File/System/Object.pm
    version: 1.06
  File::System::Passthrough:
    file: lib/File/System/Passthrough.pm
    version: 1.02
  File::System::Real:
    file: lib/File/System/Real.pm
    version: 1.05
  File::System::Table:
    file: lib/File/System/Table.pm
    version: 1.03
  File::System::Test:
    file: lib/File/System/Test.pm
    version: 1.03
generated_by: Module::Build version 0.261
